title: 4AllUsers
description: "Siber Güvenlik Bloğu,Hack The Box ve makina çözümleri, yazılar ve diğer şeyler"
author:
  name: "Tuğcan Özel"
  email: "tugcanozel@gmail.com"
  url: "0x4All.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:categories/:title/
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "4AllUsers"
year : "2019"
